sudo: required
services:
    - Docker

before_install:
    - docker build -t rotemtzuk/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true rotemtzuk/react=test npm run test -- --coverage

after_success:
    - docker build -t rotemtzuk/multi-client ./client
    - docker build -t rotemtzuk/multi-nginx ./nginx
    - docker build -t rotemtzuk/multi-worker ./worker
    - docker build -t rotemtzuk/multi-server ./server

    # Login to Docker CLI
    - echo "DOCKER_PASSWORD" | docker login -u "DOCKER_ID" --password-stdin
    # Take these images and push them to DockerHub
    - docker push rotemtzuk/multi-client    
    - docker push rotemtzuk/multi-nginx
    - docker push rotemtzuk/multi-worker
    - docker push rotemtzuk/multi-server


deploy:
    edge: true
    provider: elasticbeanstalk
    region: "eu-west-1"
    app: "react-docker"
    env: "ReactDocker-env"
    bucket_name: "elasticbeanstalk-eu-west-1-347610968691"
    bucket_path: "react-docker"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
